### ISSUE TITLE
Catch input output error when scraping PMIDs

### ISSUE THREAD

**Issue by ytpillai** [NanoNLP/PaperScraper#6]
We talked about it in the lab

**Comment by ytpillai** [comment]
https://github.com/NanoNLP/PaperScraper/blob/8adb7155eb282a7f8783d9fb4a1166dddcf8cacf/paperscraper/aggregators/pubmed_aggregator.py#L36

**Comment by CoreySutphin** [comment]
Closed in Pull Request #8
